### ISSUE TITLE
Get file content size instead of declaring an array with the fixed size.

### ISSUE THREAD

**Issue by asryansergey** [luizabaghdasaryan/homeworks_os#1]
You can use `stat` or `lseek` system calls to determine the size of given file _(it's content size)_.

https://github.com/luizabaghdasaryan/homeworks_os/blob/937dffa69f7de53777e4bf3b7dcc20fa61a5b816/homework1/print_contents_of_files.c#L61

**Comment by luizabaghdasaryan** [comment]
changed using stat

**Comment by asryansergey** [comment]
Well done!
